services:
  - type: web
    name: dpp-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URI
        sync: false
